In [ ]:
import mysql.connector

conn = mysql.connector.connect(host='localhost',password='1022',user='root')

if conn.is_connected():
    cursor = conn.cursor()

    cursor.execute("SHOW DATABASES")
    databases = cursor.fetchall()
    for database in databases:
        print(database[0])
    cursor.close()
    conn.close()

In [ ]:
import mysql.connector
import pandas as pd

# Connect to MySQL server
def Mysql_engine():
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password='1022',
        database='youtube'
    )
    return conn

def channel_list():
    conn = Mysql_engine() 
    if conn.is_connected():
        # Query to select all tables in the database
        query = "select Channel_Name from channel_data;"

        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, conn)
        
            # Close the connection
        conn.close()
        # Print the DataFrame containing table names
    return tables_df


 
a = channel_list()

pd.DataFrame(a)

In [ ]:
# count channel data
def channel_count():
    conn = Mysql_engine() 
    if conn.is_connected():
        # Query to select all tables in the database
        query = "select count(*) from channel_data;"

        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, conn)
        
            # Close the connection
        conn.close()
        # Print the DataFrame containing table names
        result = pd.DataFrame(tables_df)
        result = result.iloc[0, 0]
    return result

a = channel_count()
a

In [ ]:
import mysql.connector

def comment_count():
    # Connect to MySQL database
    mydb = mysql.connector.connect(
        host='localhost',
        user='root',
        password='1022',
        database="youtube"
    )

    # Check if the connection is successful
    if mydb.is_connected():
        # Create a cursor object
        mycursor = mydb.cursor()

        try:
            # Query to count all records in the comment_data table
            query = "SELECT COUNT(*) FROM comment_data;"
            mycursor.execute(query)
            result = mycursor.fetchone()[0]
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            mydb.close()

# Example usage
comment_count()

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

# Database connection string
DATABASE_URL = 'mysql+mysqlconnector://root:1022@localhost/youtube'

# Create database engine
engine = create_engine(DATABASE_URL)

def video_table():
    try:
        # Query to select all records from the v_data table
        query = "SELECT * FROM v_data;"
        
        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, engine)
        
        # Print the DataFrame containing table names
        # print(tables_df)
        
        # Return the DataFrame
        return tables_df
    except Exception as e:
        print("Error executing query:", e)

# Example usage
video_table()

In [ ]:
# count channel data
def playlist_count():
    conn = Mysql_engine() 
    if conn.is_connected():
        # Query to select all tables in the database
        query = "select count(*) from playlist_data;"

        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, conn)
        
            # Close the connection
        conn.close()
        # Print the DataFrame containing table names
        result = pd.DataFrame(tables_df)
        result = result.iloc[0, 0]
    return result

a = playlist_count()
a

In [ ]:

# count channel data
def comment_count():
    conn = Mysql_engine() 
    if conn.is_connected():
        # Query to select all tables in the database
        query = "select count(*) from comment_data;"

        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, conn)
        
            # Close the connection
        conn.close()
        # Print the DataFrame containing table names
        result = pd.DataFrame(tables_df)
        result = result.iloc[0, 0]
    return result

In [ ]:
def vedio_table():
    conn = Mysql_engine() 
    if conn.is_connected():
        # Query to select all tables in the database
        query = "select * from v_data;"
        # Use pandas to read the query result into a DataFrame
        tables_df = pd.read_sql(query, conn)
        
            # Close the connection
        conn.close()
        # Print the DataFrame containing table names
    return tables_df

vedio_table()

In [ ]:
a = channel_count()
a

In [ ]:
def inc():
    temp = [0,0,0,0]
    ch_count = channel_count()
    ch_result = ch_count - temp[0]
    temp.insert(0,ch_count)
    
    pc = playlist_count()
    pc_result = pc - temp[1]
    temp.insert(1,pc)
    
    cc = comment_count()
    cc_result = cc - temp[2]
    temp.insert(1,cc)

    return ch_result,pc_result,cc_result

ch,play,com = inc()
print(ch)
print(play)
print(com)

In [ ]:
import mysql.connector
import pandas as pd
def Mysql_engine():
    conn = mysql.connector.connect(
        host='localhost',
        user='root',
        password='1022',
        database='youtube'
    )
    
    return conn

def query3():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select v_data.view_count,v_data.video_name ,channel_data.Channel_Name from v_data
                        join channel_data on channel_data.Channel_Id = v_data.channel_id
                        order by view_count desc
                        limit 10;"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()

In [ ]:
pd.DataFrame(query3(),columns=['View Count', 'Video Name', 'Channel Name'])

In [ ]:
def query1():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select  channel_data.Channel_Name,v_data.video_name from v_data 
                join channel_data on channel_data.Channel_Id = v_data.channel_id;"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()

In [ ]:
pd.DataFrame(query1(),columns=['channel_name','vedio Tittle'])

In [ ]:
def query2():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """SELECT v_data.channel_id, channel_data.Channel_Name, COUNT(video_id) AS video_count
                        FROM v_data 
                        join channel_data on channel_data.Channel_Id = v_data.channel_id
                        GROUP BY channel_id order by vedio_count desc limit 1;"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()
pd.DataFrame(query2(),columns=['channel_id','channel_name','vedio_count'])

In [ ]:
def query4():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select count(comment_id) as cc ,vedio_id, v_data.video_name from comment_data
                join v_data on v_data.video_id = comment_data.vedio_id
                group by vedio_id order by cc desc"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()

In [ ]:
pd.DataFrame(query4(),columns=['comment_count','vedio_id','vedio_name'])

In [ ]:
def query5():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select (like_count) AS Highest_Like,video_name, channel_data.channel_name
            FROM v_data join channel_data on channel_data.channel_id = v_data.channel_id 
            order by Highest_Like desc limit 3;"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()
            
pd.DataFrame(query5(),columns=['Likes','Vedio Tittle','channel_name'])

In [ ]:
def query6():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select like_count,video_name from v_data order by like_count desc;"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()
            
pd.DataFrame(query6(),columns=['Likes','Vedio_name'])

In [ ]:
def query8():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """SELECT published,video_name,channel_data.channel_name
                    FROM v_data join channel_data on channel_data.channel_id = v_data.channel_id
                    WHERE published LIKE '2022%'
                    order by published"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()
            
pd.DataFrame(query8(),columns=['published', 'video_name', 'channel_name'])

In [ ]:
def query10():
    conn = Mysql_engine() 
    if conn.is_connected():
    # Create a cursor object
        mycursor = conn.cursor()
        try:
            # Query to count all records in the comment_data table
            query = """select vedio_id, count(comment_id) as cc , channel_data.channel_name from comment_data 
                    join v_data on v_data.video_id = comment_data.vedio_id
                    join channel_data on channel_data.channel_id = v_data.channel_id
                    group by(vedio_id) order by cc desc"""
            mycursor.execute(query)
            result = mycursor.fetchall()
            return (result)
        except Exception as e:
            print("Error executing query:", e)
        finally:
            mycursor.close()
            conn.close()
            
pd.DataFrame(query10(),columns=["vedio_id", "comment count", "channel_name"])